# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

make_AR_prec_matrix <- function(dim, rho) {
    .Call(`_stdmatern_make_AR_prec_matrix`, dim, rho)
}

make_matern_prec_matrix <- function(dim, rho, nu) {
    .Call(`_stdmatern_make_matern_prec_matrix`, dim, rho, nu)
}

compute_marginal_variances <- function(Q) {
    .Call(`_stdmatern_compute_marginal_variances`, Q)
}

make_standardized_matern <- function(dim, rho, nu) {
    .Call(`_stdmatern_make_standardized_matern`, dim, rho, nu)
}

make_standardized_matern_cholesky <- function(dim, rho, nu) {
    .Call(`_stdmatern_make_standardized_matern_cholesky`, dim, rho, nu)
}

dmvn_chol_cpp <- function(X, L) {
    .Call(`_stdmatern_dmvn_chol_cpp`, X, L)
}

matern_mvn_density_cpp <- function(X, dim, rho, nu) {
    .Call(`_stdmatern_matern_mvn_density_cpp`, X, dim, rho, nu)
}

fast_marginal_variances <- function(Q1) {
    .Call(`_stdmatern_fast_marginal_variances`, Q1)
}

log_density_eigen <- function(x, eigenvalue, eigenvector) {
    .Call(`_stdmatern_log_density_eigen`, x, eigenvalue, eigenvector)
}

matern_mvn_density_eigen <- function(X, dim, rho, nu) {
    .Call(`_stdmatern_matern_mvn_density_eigen`, X, dim, rho, nu)
}

